### ISSUE TITLE
Question: Ok for you if I use your notes in some of my repositories?

### ISSUE THREAD

**Issue by ekoepplin** [brynhayder/statistical_inference#1]
Hi Bryn, I'm reading "Statistical Inference" for one of my courses. In that regard, I thought it would make more fun to create a jupyter book which uses some of those concepts and illustrates them by means of numerical examples using python. Kind of "Statistical Inference - Python companion"
Do you mind if I use your notes in that jupyter book? It would be an open github repository comprised of chapters where each chapter is a chapter comprised of your notes and python code. 
Best
Eugen

**Comment by brynhayder** [comment]
Hi Eugen. 

That's fine as long as you acknowledge the source of the notes (i.e. me and the repo).

I'm excited to see what you produce, let me know when you're done!
